# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -n "$SSH_CLIENT" ]; then
#	PS1="{\u@\[\033[33m*SSH*\033[0m\]\h \W}$ "
	PS1='\[\e[1;33;40m\]\u@\h:\w *SSH* \[\e[0m\]'
else
#	PS1="\e[1;37m\e[44m{\u@\h \W}\e[m$ "
	PS1='\[\e[1;31;47m\]\w> \[\e[0m\]'
fi

alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias cls='clear'
